apiVersion: v1
kind: Service
metadata:
  name: springbootmicroservicescontainerization
spec:
  selector:
    app: springbootmicroservicescontainerization
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort